/**
 * @traqr/core — Alias Generator
 *
 * Generates per-project shell alias files for multi-project support.
 * Each project gets its own file at ~/.traqr/aliases/{slug}.sh.
 * The primary project also gets generic aliases (z1, c1, etc.).
 *
 * Usage:
 *   generateAliasFile(config, { isPrimary: true })
 *   → writes ~/.traqr/aliases/nooktraqr.sh
 */

import * as fs from 'fs';
import * as path from 'path';
import type { TraqrConfig } from './config-schema.js';
import { generateSlots } from './template-engine.js';

// ============================================================
// Types
// ============================================================

export interface AliasGeneratorOptions {
  /** Whether this is the primary project (gets generic z1/c1 aliases too) */
  isPrimary: boolean;
  /** Override output directory (default: ~/.traqr/aliases/) */
  outputDir?: string;
}

interface SlotAliasInfo {
  name: string;
  branch: string;
  port: number;
  category: 'marketing' | 'feature' | 'bugfix' | 'devops' | 'guardian' | 'analysis';
  /** Short alias suffix: "1", "2", "b1", "b2", "d1", "d2", "a" */
  aliasSuffix: string;
  /** Emoji label for Claude tab title */
  tabLabel: string;
}

// ============================================================
// Alias Suffix Mapping
// ============================================================

function getAliasSuffix(slot: { name: string; category: string }): string {
  if (slot.category === 'analysis') return 'a';
  if (slot.category === 'guardian') return 'g';
  const num = slot.name.replace(/\D/g, '');
  switch (slot.category) {
    case 'marketing': return `k${num}`;
    case 'feature': return num;
    case 'bugfix': return `b${num}`;
    case 'devops': return `d${num}`;
    default: return slot.name;
  }
}

function getTabLabel(slot: { name: string; category: string }): string {
  const num = slot.name.replace(/\D/g, '');
  switch (slot.category) {
    case 'marketing': return `Marketing ${num}`;
    case 'feature': return `Feature ${num}`;
    case 'bugfix': return `Bugfix ${num}`;
    case 'devops': return `DevOps ${num}`;
    case 'guardian': return 'Grunt';
    case 'analysis': return 'Analysis';
    default: return slot.name;
  }
}

// ============================================================
// Generator
// ============================================================

/**
 * Generate the shell alias file content for a project.
 * Returns the file content as a string.
 */
export function generateAliasContent(
  config: TraqrConfig,
  options: AliasGeneratorOptions,
): string {
  const prefix = config.aliasPrefix || config.prefix.slice(0, 2);
  const displayName = config.project.displayName || config.project.name;
  const repoPath = config.project.repoPath;
  const worktreesPath = config.project.worktreesPath;
  const P = config.prefix.toUpperCase();
  const ghOrgRepo = config.project.ghOrgRepo || '';
  const apiBase = config.daemon?.apiBase || `http://localhost:${config.ports.main}/api`;
  const shipEnvVar = config.shipEnvVar || `${P}_SHIP_AUTHORIZED`;

  const slots: SlotAliasInfo[] = generateSlots(config).map(s => ({
    ...s,
    aliasSuffix: getAliasSuffix(s),
    tabLabel: getTabLabel(s),
  }));

  const lines: string[] = [];

  // Header
  lines.push('#!/bin/bash');
  lines.push(`# =============================================================================`);
  lines.push(`# ${displayName} — Traqr Multi-Slot Aliases (prefix: ${prefix})`);
  lines.push(`# Generated by Traqr. Re-generate with: traqr render`);
  lines.push(`# =============================================================================`);
  lines.push('');

  // ANSI color variables (guarded — duplicated from shell-init.sh so alias files work standalone)
  lines.push('# ANSI color variables (shared across project files)');
  lines.push('if [ -z "$_C_RESET" ]; then');
  lines.push("_C_RESET=$'\\033[0m'");
  lines.push("_C_BOLD=$'\\033[1m'");
  lines.push("_C_DIM=$'\\033[2m'");
  lines.push("_C_CYAN=$'\\033[0;36m'");
  lines.push("_C_GREEN=$'\\033[0;32m'");
  lines.push("_C_YELLOW=$'\\033[0;33m'");
  lines.push("_C_BLUE=$'\\033[0;34m'");
  lines.push("_C_PURPLE=$'\\033[0;35m'");
  lines.push("_C_RED=$'\\033[0;31m'");
  lines.push("_C_WHITE=$'\\033[1;37m'");
  lines.push("_C_BCYAN=$'\\033[1;36m'");
  lines.push("_C_BGREEN=$'\\033[1;32m'");
  lines.push("_C_BYELLOW=$'\\033[1;33m'");
  lines.push("_C_BBLUE=$'\\033[1;34m'");
  lines.push("_C_BPURPLE=$'\\033[1;35m'");
  lines.push('fi');
  lines.push('');

  // Base paths
  lines.push(`export ${P}_MAIN="${repoPath}"`);
  lines.push(`export ${P}_WORKTREES="${worktreesPath}"`);
  lines.push(`${P}_API="\${TRAQR_API_BASE:-${apiBase}}"`);
  lines.push('');

  // Port exports
  lines.push(`export ${P}_PORT_MAIN=${config.ports.main}`);
  for (const s of slots) {
    lines.push(`export ${P}_PORT_${s.name.toUpperCase()}=${s.port}`);
  }
  lines.push('');

  // Claude launcher helper (with agent-done notification + control-center idle)
  lines.push(`_${prefix}_claude() {`);
  lines.push(`    local label="$1"`);
  lines.push(`    local dir="$2"`);
  lines.push(`    local slot=$(basename "$dir")`);
  lines.push(`    cd "$dir"`);
  lines.push(`    printf '\\e]0;%s\\a' "$label"`);
  lines.push(`    printf '\\e]1;%s\\a' "$label"`);
  lines.push(`    CLAUDE_CODE_DISABLE_TERMINAL_TITLE=1 claude`);
  lines.push(`    printf '\\e]0;%s - done\\a' "$label"`);
  lines.push(`    printf '\\e]1;%s - done\\a' "$label"`);
  lines.push(`    osascript -e "display notification \\"\$label: Session ended\\" with title \\"Agent Done\\" sound name \\"Glass\\"" 2>/dev/null &`);
  lines.push(`    curl -s --max-time 3 -X POST "\$${P}_API/control-center/state" \\`);
  lines.push(`        -H "Content-Type: application/json" \\`);
  lines.push(`        -d "{\\"slot\\":\\"$slot\\",\\"phase\\":\\"idle\\"}" > /dev/null 2>&1 &`);
  lines.push('}');
  lines.push('');

  // ---- Prefixed aliases (always generated) ----
  lines.push(`# Prefixed aliases: ${prefix}·`);

  // Jump aliases: {prefix}{suffix} → cd to worktree
  lines.push(`alias ${prefix}m='cd "$${P}_MAIN" && pwd'`);
  for (const s of slots) {
    lines.push(`alias ${prefix}${s.aliasSuffix}='cd "$${P}_WORKTREES/${s.name}" && pwd'`);
  }
  lines.push('');

  // Claude aliases: {prefix}c{suffix} → cd + claude
  lines.push(`${prefix}cm() { _${prefix}_claude "Main" "$${P}_MAIN"; }`);
  for (const s of slots) {
    lines.push(`${prefix}c${s.aliasSuffix}() { _${prefix}_claude "${s.tabLabel}" "$${P}_WORKTREES/${s.name}"; }`);
  }
  lines.push('');

  // ---- Generic aliases (only for primary project) ----
  if (options.isPrimary) {
    lines.push('# Generic aliases (primary project)');
    lines.push(`alias zm='cd "$${P}_MAIN" && pwd'`);
    for (const s of slots) {
      const genJump = s.category === 'marketing' ? `zk${s.name.replace(/\D/g, '')}` :
        s.category === 'feature' ? `z${s.name.replace(/\D/g, '')}` :
        s.category === 'bugfix' ? `zb${s.name.replace(/\D/g, '')}` :
        s.category === 'devops' ? `zd${s.name.replace(/\D/g, '')}` :
        s.category === 'guardian' ? 'zg' :
        s.category === 'analysis' ? 'za' : null;
      if (genJump) {
        lines.push(`alias ${genJump}='cd "$${P}_WORKTREES/${s.name}" && pwd'`);
      }
    }
    lines.push('');

    lines.push(`cm() { _${prefix}_claude "Main" "$${P}_MAIN"; }`);
    for (const s of slots) {
      const genClaude = s.category === 'marketing' ? `ck${s.name.replace(/\D/g, '')}` :
        s.category === 'feature' ? `c${s.name.replace(/\D/g, '')}` :
        s.category === 'bugfix' ? `cb${s.name.replace(/\D/g, '')}` :
        s.category === 'devops' ? `cd${s.name.replace(/\D/g, '')}` :
        s.category === 'guardian' ? 'cg' :
        s.category === 'analysis' ? 'ca' : null;
      if (genClaude) {
        lines.push(`${genClaude}() { _${prefix}_claude "${s.tabLabel}" "$${P}_WORKTREES/${s.name}"; }`);
      }
    }
    lines.push('');
  }

  // ================================================================
  // Slot management functions
  // ================================================================

  // ---- {prefix}-slots: Fancy box-drawing slot status table ----
  const slotInfoArray = slots.map(s => `"${s.name}:${s.branch}:${prefix}c${s.aliasSuffix}/${prefix}${s.aliasSuffix}"`).join(' ');
  lines.push(`# Slot management: ${config.prefix}-slots, ${config.prefix}-sync, ${config.prefix}-dev`);
  lines.push(`${config.prefix}-slots() {`);
  lines.push(`    local current_dir=$(pwd)`);
  lines.push('');
  lines.push(`    echo ""`);
  lines.push(`    echo -e "  \${_C_BCYAN}${displayName} Slot Status\${_C_RESET}"`);
  lines.push(`    echo ""`);
  lines.push('    echo -e "  ${_C_DIM}╭──────────┬────────────────────┬───────┬─────────┬──────────────╮${_C_RESET}"');
  lines.push('    echo -e "  ${_C_DIM}│${_C_RESET} ${_C_BOLD}Slot${_C_RESET}     ${_C_DIM}│${_C_RESET} ${_C_BOLD}Branch${_C_RESET}             ${_C_DIM}│${_C_RESET} ${_C_BOLD}Ahead${_C_RESET} ${_C_DIM}│${_C_RESET} ${_C_BOLD}Changes${_C_RESET} ${_C_DIM}│${_C_RESET} ${_C_BOLD}Status${_C_RESET}       ${_C_DIM}│${_C_RESET}"');
  lines.push('    echo -e "  ${_C_DIM}├──────────┼────────────────────┼───────┼─────────┼──────────────┤${_C_RESET}"');
  lines.push('');
  lines.push(`    local available_slots=()`);
  lines.push(`    local open_prs=()`);
  lines.push(`    local slots=(${slotInfoArray})`);
  lines.push('');
  lines.push('    for slot_info in "${slots[@]}"; do');
  lines.push('        local slot=$(echo "$slot_info" | cut -d: -f1)');
  lines.push('        local expected_branch=$(echo "$slot_info" | cut -d: -f2)');
  lines.push('        local aliases=$(echo "$slot_info" | cut -d: -f3)');
  lines.push(`        local p="$${P}_WORKTREES/$slot"`);
  lines.push('');
  lines.push('        if [ ! -d "$p" ]; then');
  lines.push('            echo -e "  ${_C_DIM}│${_C_RESET} ${_C_DIM}${slot}${_C_RESET}$(printf \'%*s\' $((8 - ${#slot})) \'\') ${_C_DIM}│${_C_RESET} ${_C_DIM}(not created)${_C_RESET}       ${_C_DIM}│${_C_RESET}   ${_C_DIM}-${_C_RESET}   ${_C_DIM}│${_C_RESET}    ${_C_DIM}-${_C_RESET}    ${_C_DIM}│${_C_RESET} ${_C_DIM}—${_C_RESET}            ${_C_DIM}│${_C_RESET}"');
  lines.push('            continue');
  lines.push('        fi');
  lines.push('');
  lines.push('        local branch=$(git -C "$p" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "?")');
  lines.push('        local ahead=$(git -C "$p" log origin/main..HEAD --oneline 2>/dev/null | wc -l | tr -d \' \')');
  lines.push('        local changes=$(git -C "$p" status --porcelain 2>/dev/null | wc -l | tr -d \' \')');
  lines.push(`        local pr=$(gh pr list --repo "${ghOrgRepo}" --head "$branch" --state open --json number --jq '.[0].number // ""' 2>/dev/null || echo "")`);
  lines.push('');
  lines.push('        local status_str status_color');
  lines.push('        local is_here=false');
  lines.push('        [[ "$current_dir" == *"$slot"* ]] && is_here=true');
  lines.push('');
  lines.push('        if [ "$is_here" = true ]; then');
  lines.push('            status_str="here <-"');
  lines.push('            status_color="${_C_BGREEN}"');
  lines.push('        elif [ -n "$pr" ]; then');
  lines.push('            status_str="PR #${pr}"');
  lines.push('            status_color="${_C_BBLUE}"');
  lines.push('            open_prs+=("#${pr} (${branch})")');
  lines.push('        elif [ "$changes" -gt 0 ]; then');
  lines.push('            status_str="wip"');
  lines.push('            status_color="${_C_BYELLOW}"');
  lines.push('        elif [ "$ahead" -gt 0 ]; then');
  lines.push('            if [ "$ahead" -eq 1 ]; then status_str="1 commit"; else status_str="${ahead} commits"; fi');
  lines.push('            status_color="${_C_YELLOW}"');
  lines.push('        else');
  lines.push('            status_str="free"');
  lines.push('            status_color="${_C_BGREEN}"');
  lines.push('            available_slots+=("${slot} (${aliases})")');
  lines.push('        fi');
  lines.push('');
  lines.push('        local slot_pad=$(printf \'%*s\' $((8 - ${#slot})) \'\')');
  lines.push('        local branch_pad=$(printf \'%*s\' $((18 - ${#branch})) \'\')');
  lines.push('        local ahead_pad=$(printf \'%*s\' $((5 - ${#ahead})) \'\')');
  lines.push('        local changes_pad=$(printf \'%*s\' $((7 - ${#changes})) \'\')');
  lines.push('        local status_display="${status_str}"');
  lines.push('        local status_pad=$(printf \'%*s\' $((12 - ${#status_display})) \'\')');
  lines.push('');
  lines.push('        echo -e "  ${_C_DIM}│${_C_RESET} ${_C_WHITE}${slot}${_C_RESET}${slot_pad} ${_C_DIM}│${_C_RESET} ${branch}${branch_pad} ${_C_DIM}│${_C_RESET} ${ahead_pad}${ahead} ${_C_DIM}│${_C_RESET} ${changes_pad}${changes} ${_C_DIM}│${_C_RESET} ${status_color}${status_display}${_C_RESET}${status_pad} ${_C_DIM}│${_C_RESET}"');
  lines.push('    done');
  lines.push('');
  lines.push('    echo -e "  ${_C_DIM}╰──────────┴────────────────────┴───────┴─────────┴──────────────╯${_C_RESET}"');
  lines.push('');
  lines.push('    if [ ${#open_prs[@]} -gt 0 ]; then');
  lines.push("        local pr_list=$(IFS=', '; echo \"${open_prs[*]}\")");
  lines.push('        echo -e "  ${_C_BBLUE}Open PRs:${_C_RESET} ${pr_list}"');
  lines.push('    fi');
  lines.push('    if [ ${#available_slots[@]} -gt 0 ]; then');
  lines.push('        local avail_list=""');
  lines.push('        for i in "${!available_slots[@]}"; do');
  lines.push('            if [ "$i" -gt 0 ]; then avail_list+=", "; fi');
  lines.push('            avail_list+="${available_slots[$i]}"');
  lines.push('        done');
  lines.push('        echo -e "  ${_C_BGREEN}Available:${_C_RESET} ${avail_list}"');
  lines.push('    fi');
  lines.push('    echo ""');
  lines.push('}');
  lines.push('');

  // ---- {prefix}-sync: Smart sync all slots with main ----
  const syncSlotNames = slots.map(s => `"${s.name}"`).join(' ');
  lines.push(`${config.prefix}-sync() {`);
  lines.push(`    echo ""`);
  lines.push(`    echo -e "  \${_C_BCYAN}${displayName} Sync\${_C_RESET} \${_C_DIM}· all slots → main\${_C_RESET}"`);
  lines.push('    echo -e "  ${_C_DIM}────────────────────────────────────────────${_C_RESET}"');
  lines.push(`    echo ""`);
  lines.push('');
  lines.push(`    echo -e "  \${_C_WHITE}main\${_C_RESET}"`);
  lines.push(`    cd "$${P}_MAIN"`);
  lines.push(`    git pull origin main 2>/dev/null`);
  lines.push(`    local main_sha=$(git rev-parse --short HEAD)`);
  lines.push('    echo -e "    ${_C_BGREEN}synced${_C_RESET} ${_C_DIM}(${main_sha})${_C_RESET}"');
  lines.push('');
  lines.push(`    local skipped_slots=()`);
  lines.push(`    local stashed_slots=()`);
  lines.push(`    local synced_count=0`);
  lines.push(`    local total_count=0`);
  lines.push(`    local slots=(${syncSlotNames})`);
  lines.push('');
  lines.push('    for slot in "${slots[@]}"; do');
  lines.push(`        local p="$${P}_WORKTREES/$slot"`);
  lines.push('        total_count=$((total_count + 1))');
  lines.push('');
  lines.push('        if [ ! -d "$p" ]; then');
  lines.push('            echo -e "  ${_C_DIM}${slot} (not created)${_C_RESET}"');
  lines.push('            continue');
  lines.push('        fi');
  lines.push('');
  lines.push('        echo -e "  ${_C_WHITE}${slot}${_C_RESET}"');
  lines.push('        git -C "$p" fetch origin main 2>/dev/null');
  lines.push("        local uncommitted=$(git -C \"$p\" status --porcelain 2>/dev/null | wc -l | tr -d ' ')");
  lines.push("        local ahead=$(git -C \"$p\" log origin/main..HEAD --oneline 2>/dev/null | wc -l | tr -d ' ')");
  lines.push('');
  lines.push('        if [ "$uncommitted" -gt 0 ]; then');
  lines.push("            local uncommitted_files=$(git -C \"$p\" status --porcelain 2>/dev/null | awk '{print $NF}')");
  lines.push('            local main_changed=$(git -C "$p" diff --name-only HEAD origin/main 2>/dev/null)');
  lines.push('            local overlap=""');
  lines.push('            if [ -n "$main_changed" ]; then');
  lines.push('                overlap=$(comm -12 <(echo "$uncommitted_files" | sort 2>/dev/null) <(echo "$main_changed" | sort 2>/dev/null) 2>/dev/null)');
  lines.push('            fi');
  lines.push('');
  lines.push('            if [ -n "$overlap" ]; then');
  lines.push("                local overlap_count=$(echo \"$overlap\" | wc -l | tr -d ' ')");
  lines.push('                echo -e "    ${_C_RED}conflict${_C_RESET} ${_C_DIM}(${overlap_count} overlapping files — commit first)${_C_RESET}"');
  lines.push('                skipped_slots+=("$slot")');
  lines.push('            else');
  lines.push('                echo -e "    ${_C_BYELLOW}stashing${_C_RESET} ${_C_DIM}(${uncommitted} files)${_C_RESET}"');
  lines.push('                local stash_msg="auto-stash-sync-$(date +%s)"');
  lines.push('                if git -C "$p" stash push -u -m "$stash_msg" 2>/dev/null; then');
  lines.push('                    git -C "$p" reset --hard origin/main 2>/dev/null');
  lines.push('                    local new_sha=$(git -C "$p" rev-parse --short HEAD)');
  lines.push("                    echo -e \"    \\${_C_BGREEN}synced\\${_C_RESET} \\${_C_DIM}(run 'git stash pop' to restore)\\${_C_RESET}\"");
  lines.push('                    stashed_slots+=("$slot")');
  lines.push('                    synced_count=$((synced_count + 1))');
  lines.push(`                    curl -s -X POST "\$${P}_API/daemon/mark-synced" \\`);
  lines.push('                        -H "Content-Type: application/json" \\');
  lines.push('                        -d "{\\"slot\\":\\"$slot\\",\\"commitSha\\":\\"$new_sha\\"}" > /dev/null 2>&1');
  lines.push('                else');
  lines.push('                    echo -e "    ${_C_RED}stash failed${_C_RESET} ${_C_DIM}— skipping${_C_RESET}"');
  lines.push('                    skipped_slots+=("$slot")');
  lines.push('                fi');
  lines.push('            fi');
  lines.push('        elif [ "$ahead" -gt 0 ]; then');
  lines.push('            echo -e "    ${_C_BYELLOW}rebasing${_C_RESET} ${_C_DIM}(${ahead} commits ahead)${_C_RESET}"');
  lines.push('            if git -C "$p" rebase origin/main 2>/dev/null; then');
  lines.push('                local new_sha=$(git -C "$p" rev-parse --short HEAD)');
  lines.push('                echo -e "    ${_C_BGREEN}rebased${_C_RESET} ${_C_DIM}(${new_sha})${_C_RESET}"');
  lines.push('                synced_count=$((synced_count + 1))');
  lines.push(`                curl -s -X POST "\$${P}_API/daemon/mark-synced" \\`);
  lines.push('                    -H "Content-Type: application/json" \\');
  lines.push('                    -d "{\\"slot\\":\\"$slot\\",\\"commitSha\\":\\"$new_sha\\"}" > /dev/null 2>&1');
  lines.push('            else');
  lines.push('                echo -e "    ${_C_RED}rebase failed${_C_RESET} ${_C_DIM}— resolve manually${_C_RESET}"');
  lines.push('                git -C "$p" rebase --abort 2>/dev/null');
  lines.push('                skipped_slots+=("$slot")');
  lines.push('            fi');
  lines.push('        else');
  lines.push('            git -C "$p" reset --hard origin/main 2>/dev/null');
  lines.push('            local new_sha=$(git -C "$p" rev-parse --short HEAD)');
  lines.push('            echo -e "    ${_C_BGREEN}synced${_C_RESET} ${_C_DIM}(${new_sha})${_C_RESET}"');
  lines.push('            synced_count=$((synced_count + 1))');
  lines.push(`            curl -s -X POST "\$${P}_API/daemon/mark-synced" \\`);
  lines.push('                -H "Content-Type: application/json" \\');
  lines.push('                -d "{\\"slot\\":\\"$slot\\",\\"commitSha\\":\\"$new_sha\\"}" > /dev/null 2>&1');
  lines.push('        fi');
  lines.push('    done');
  lines.push('');
  lines.push('    echo ""');
  lines.push('    echo -e "  ${_C_DIM}────────────────────────────────────────────${_C_RESET}"');
  lines.push('');
  lines.push('    if [ ${#skipped_slots[@]} -eq 0 ] && [ ${#stashed_slots[@]} -eq 0 ]; then');
  lines.push('        echo -e "  ${_C_BGREEN}All slots synced${_C_RESET} ${_C_DIM}(${synced_count}/${total_count})${_C_RESET}"');
  lines.push('    else');
  lines.push('        if [ ${#skipped_slots[@]} -gt 0 ]; then');
  lines.push('            echo -e "  ${_C_RED}Skipped:${_C_RESET} ${skipped_slots[*]} ${_C_DIM}— resolve conflicts, then re-sync${_C_RESET}"');
  lines.push('        fi');
  lines.push('        if [ ${#stashed_slots[@]} -gt 0 ]; then');
  lines.push("            echo -e \"  \\${_C_BYELLOW}Stashed:\\${_C_RESET} \\${stashed_slots[*]} \\${_C_DIM}— run 'git stash pop' to restore\\${_C_RESET}\"");
  lines.push('        fi');
  lines.push('    fi');
  lines.push('    echo ""');
  lines.push('}');
  lines.push('');

  // ---- {prefix}-reset: Interactive slot reset with confirmation ----
  const resetCases = slots.map(s => `        ${s.name}) branch="${s.branch}" ;;`).join('\n');
  const slotNameList = slots.map(s => s.name).join(', ');
  lines.push(`${config.prefix}-reset() {`);
  lines.push(`    local slot="$1"`);
  lines.push('');
  lines.push('    if [ -z "$slot" ]; then');
  lines.push(`        echo ""`);
  lines.push(`        echo -e "  \${_C_BCYAN}${config.prefix}-reset\${_C_RESET} \${_C_DIM}<slot>\${_C_RESET}"`);
  lines.push(`        echo ""`);
  lines.push('        echo -e "  ${_C_DIM}Resets a slot to match main (discards all local work).${_C_RESET}"');
  lines.push(`        echo ""`);
  lines.push(`        echo -e "  \${_C_WHITE}Slots:\${_C_RESET} ${slotNameList}"`);
  lines.push(`        echo ""`);
  lines.push('        return 1');
  lines.push('    fi');
  lines.push('');
  lines.push('    local branch');
  lines.push('    case "$slot" in');
  lines.push(resetCases);
  lines.push('        *)');
  lines.push('            echo "Unknown slot: $slot"');
  lines.push('            return 1');
  lines.push('            ;;');
  lines.push('    esac');
  lines.push('');
  lines.push(`    local p="$${P}_WORKTREES/$slot"`);
  lines.push('    if [ ! -d "$p" ]; then');
  lines.push(`        echo "Slot $slot doesn't exist at $p"`);
  lines.push(`        echo "   Run ${config.prefix}-setup to create all slots"`);
  lines.push('        return 1');
  lines.push('    fi');
  lines.push('');
  lines.push(`    echo ""`);
  lines.push('    echo -e "  ${_C_RED}This will discard all uncommitted changes in ${_C_WHITE}${slot}${_C_RESET}"');
  lines.push('    echo -e "  ${_C_DIM}Path:   ${p}${_C_RESET}"');
  lines.push('    echo -e "  ${_C_DIM}Branch: ${branch}${_C_RESET}"');
  lines.push(`    echo ""`);
  lines.push('    read -p "  Continue? (y/N) " confirm');
  lines.push('');
  lines.push('    if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then');
  lines.push('        echo -e "  ${_C_DIM}Cancelled.${_C_RESET}"');
  lines.push('        return 0');
  lines.push('    fi');
  lines.push('');
  lines.push(`    echo ""`);
  lines.push('    cd "$p"');
  lines.push('    git fetch origin main 2>/dev/null');
  lines.push('    git reset --hard origin/main 2>/dev/null');
  lines.push('    local new_sha=$(git rev-parse --short HEAD)');
  lines.push('    echo -e "  ${_C_BGREEN}${slot} reset to main${_C_RESET} ${_C_DIM}(${new_sha})${_C_RESET}"');
  lines.push(`    echo ""`);
  lines.push('}');
  lines.push('');

  // ---- {prefix}-ship: Push + create/find PR + Slack notify ----
  lines.push(`${config.prefix}-ship() {`);
  lines.push(`    local branch=$(git rev-parse --abbrev-ref HEAD)`);
  lines.push(`    local title="$1"`);
  lines.push('');
  lines.push('    if [ "$branch" = "main" ]; then');
  lines.push(`        echo ""`);
  lines.push('        echo -e "  ${_C_RED}Cannot ship from main.${_C_RESET} ${_C_DIM}Use a worktree slot.${_C_RESET}"');
  lines.push(`        echo ""`);
  lines.push('        return 1');
  lines.push('    fi');
  lines.push('');
  lines.push(`    local current_dir=$(pwd)`);
  lines.push(`    local slot_name="unknown"`);
  for (const s of slots) {
    lines.push(`    [[ "$current_dir" == *"${s.name}"* ]] && slot_name="${s.name}"`);
  }
  lines.push('');
  lines.push(`    echo ""`);
  lines.push('    echo -e "  ${_C_BCYAN}Shipping${_C_RESET} ${_C_WHITE}${branch}${_C_RESET} ${_C_DIM}from ${slot_name}${_C_RESET}"');
  lines.push('    echo -e "  ${_C_DIM}────────────────────────────────────────────${_C_RESET}"');
  lines.push(`    echo ""`);
  lines.push('');
  lines.push('    echo -e "  ${_C_DIM}pushing...${_C_RESET}"');
  lines.push('    git push -u origin "$branch" 2>/dev/null');
  lines.push('    echo -e "  ${_C_BGREEN}pushed${_C_RESET}"');
  lines.push('');
  lines.push(`    local existing_pr=$(gh pr list --repo "${ghOrgRepo}" --head "$branch" --json number --jq '.[0].number' 2>/dev/null)`);
  lines.push('');
  lines.push('    if [ -n "$existing_pr" ]; then');
  lines.push('        echo -e "  ${_C_BBLUE}PR #${existing_pr}${_C_RESET} ${_C_DIM}already exists${_C_RESET}"');
  lines.push('        echo -e "  ${_C_DIM}notifying Slack...${_C_RESET}"');
  lines.push(`        curl -s -X POST "\$${P}_API/github/pr?action=notify&pr=$existing_pr&slot=$slot_name" > /dev/null 2>&1`);
  lines.push('        echo -e "  ${_C_BGREEN}notified${_C_RESET}"');
  lines.push('    else');
  lines.push('        echo -e "  ${_C_DIM}creating PR...${_C_RESET}"');
  lines.push('        if [ -z "$title" ]; then');
  lines.push('            gh pr create --fill --base main 2>/dev/null');
  lines.push('        else');
  lines.push('            gh pr create --title "$title" --base main --fill 2>/dev/null');
  lines.push('        fi');
  lines.push(`        local new_pr=$(gh pr list --repo "${ghOrgRepo}" --head "$branch" --json number --jq '.[0].number' 2>/dev/null)`);
  lines.push('        if [ -n "$new_pr" ]; then');
  lines.push('            echo -e "  ${_C_BBLUE}PR #${new_pr}${_C_RESET} ${_C_DIM}created${_C_RESET}"');
  lines.push('            echo -e "  ${_C_DIM}notifying Slack...${_C_RESET}"');
  lines.push(`            curl -s -X POST "\$${P}_API/github/pr?action=notify&pr=$new_pr&slot=$slot_name" > /dev/null 2>&1`);
  lines.push('            echo -e "  ${_C_BGREEN}notified${_C_RESET}"');
  lines.push('        fi');
  lines.push('    fi');
  lines.push('');
  lines.push(`    echo ""`);
  lines.push('    echo -e "  ${_C_DIM}────────────────────────────────────────────${_C_RESET}"');
  lines.push('    echo -e "  ${_C_BGREEN}Shipped.${_C_RESET} ${_C_DIM}Guardian will auto-merge when CI passes.${_C_RESET}"');
  lines.push(`    echo ""`);
  lines.push('}');
  lines.push('');

  // ---- {prefix}-prs: List open PRs with slot context ----
  lines.push(`${config.prefix}-prs() {`);
  lines.push(`    echo ""`);
  lines.push(`    echo -e "  \${_C_BCYAN}${displayName} Open PRs\${_C_RESET}"`);
  lines.push(`    echo ""`);
  lines.push(`    local prs=$(gh pr list --repo "${ghOrgRepo}" --state open --json number,title,headRefName --jq '.[] | "  \\(.number)|\\(.headRefName)|\\(.title)"' 2>/dev/null)`);
  lines.push('    if [ -z "$prs" ]; then');
  lines.push('        echo -e "  ${_C_DIM}No open PRs.${_C_RESET}"');
  lines.push('    else');
  lines.push("        while IFS='|' read -r num branch title; do");
  lines.push('            echo -e "  ${_C_BBLUE}#${num}${_C_RESET}  ${_C_DIM}${branch}${_C_RESET}"');
  lines.push('            echo -e "       ${title}"');
  lines.push('        done <<< "$prs"');
  lines.push('    fi');
  lines.push(`    echo ""`);
  lines.push('}');
  lines.push('');

  // ---- {prefix}-ports: Port assignment table ----
  lines.push(`${config.prefix}-ports() {`);
  lines.push(`    echo ""`);
  lines.push(`    echo -e "  \${_C_BCYAN}${displayName} Port Assignments\${_C_RESET}"`);
  lines.push(`    echo ""`);
  lines.push('    echo -e "  ${_C_DIM}╭──────────┬──────┬────────────────────────────╮${_C_RESET}"');
  lines.push('    echo -e "  ${_C_DIM}│${_C_RESET} ${_C_BOLD}Slot${_C_RESET}     ${_C_DIM}│${_C_RESET} ${_C_BOLD}Port${_C_RESET} ${_C_DIM}│${_C_RESET} ${_C_BOLD}URL${_C_RESET}                        ${_C_DIM}│${_C_RESET}"');
  lines.push('    echo -e "  ${_C_DIM}├──────────┼──────┼────────────────────────────┤${_C_RESET}"');
  // Main row
  lines.push(`    echo -e "  \${_C_DIM}│\${_C_RESET} \${_C_WHITE}main\${_C_RESET}     \${_C_DIM}│\${_C_RESET} ${config.ports.main} \${_C_DIM}│\${_C_RESET} \${_C_CYAN}http://localhost:${config.ports.main}\${_C_RESET}    \${_C_DIM}│\${_C_RESET}"`);
  // Slot rows
  for (const s of slots) {
    const namePad = ' '.repeat(Math.max(0, 8 - s.name.length));
    lines.push(`    echo -e "  \${_C_DIM}│\${_C_RESET} \${_C_WHITE}${s.name}\${_C_RESET}${namePad} \${_C_DIM}│\${_C_RESET} ${s.port} \${_C_DIM}│\${_C_RESET} \${_C_CYAN}http://localhost:${s.port}\${_C_RESET}    \${_C_DIM}│\${_C_RESET}"`);
  }
  lines.push('    echo -e "  ${_C_DIM}╰──────────┴──────┴────────────────────────────╯${_C_RESET}"');
  lines.push(`    echo ""`);
  lines.push(`    echo -e "  \${_C_DIM}Run\${_C_RESET} \${_C_WHITE}${config.prefix}-dev\${_C_RESET} \${_C_DIM}in any slot to auto-start on the correct port.\${_C_RESET}"`);
  lines.push(`    echo ""`);
  lines.push('}');
  lines.push('');

  // ---- {prefix}-setup: Create worktrees for all slots ----
  const setupSlotArray = slots.map(s => `"${s.name}:${s.branch}"`).join(' ');
  lines.push(`${config.prefix}-setup() {`);
  lines.push(`    echo ""`);
  lines.push(`    echo -e "  \${_C_BCYAN}${displayName} Setup\${_C_RESET} \${_C_DIM}· multi-slot worktree system\${_C_RESET}"`);
  lines.push('    echo -e "  ${_C_DIM}────────────────────────────────────────────${_C_RESET}"');
  lines.push(`    echo ""`);
  lines.push('');
  lines.push(`    cd "$${P}_MAIN"`);
  lines.push(`    mkdir -p "$${P}_WORKTREES"`);
  lines.push('');
  lines.push(`    local slots=(${setupSlotArray})`);
  lines.push('    local created=0');
  lines.push('    local existed=0');
  lines.push('');
  lines.push('    for slot_info in "${slots[@]}"; do');
  lines.push('        local slot="${slot_info%%:*}"');
  lines.push('        local branch="${slot_info##*:}"');
  lines.push(`        local p="$${P}_WORKTREES/$slot"`);
  lines.push('');
  lines.push('        if [ -d "$p" ]; then');
  lines.push('            echo -e "  ${_C_DIM}${slot}${_C_RESET} ${_C_DIM}— exists${_C_RESET}"');
  lines.push('            existed=$((existed + 1))');
  lines.push('        else');
  lines.push('            echo -e "  ${_C_WHITE}${slot}${_C_RESET} ${_C_DIM}(${branch})${_C_RESET}"');
  lines.push('            if git show-ref --verify --quiet "refs/heads/$branch" || git show-ref --verify --quiet "refs/remotes/origin/$branch"; then');
  lines.push('                git worktree add "$p" "$branch" 2>/dev/null || git worktree add "$p" -b "$branch"');
  lines.push('            else');
  lines.push('                git worktree add "$p" -b "$branch"');
  lines.push('            fi');
  lines.push('');
  lines.push(`            if [ -f "$${P}_MAIN/.env.local" ]; then`);
  lines.push(`                ln -sf "$${P}_MAIN/.env.local" "$p/.env.local"`);
  lines.push('            fi');
  lines.push('            echo -e "    ${_C_BGREEN}created${_C_RESET}"');
  lines.push('            created=$((created + 1))');
  lines.push('        fi');
  lines.push('    done');
  lines.push('');
  lines.push(`    echo ""`);
  lines.push('    echo -e "  ${_C_DIM}────────────────────────────────────────────${_C_RESET}"');
  lines.push('    echo -e "  ${_C_BGREEN}Done${_C_RESET} ${_C_DIM}— ${created} created, ${existed} already existed${_C_RESET}"');
  lines.push(`    echo ""`);
  lines.push('}');
  lines.push('');

  // Dev server
  lines.push(`${config.prefix}-dev() {`);
  lines.push(`    local current_dir=$(pwd)`);
  lines.push(`    local port=$${P}_PORT_MAIN slot="main"`);
  for (const s of slots) {
    lines.push(`    [[ "$current_dir" == *"${s.name}"* ]] && port=$${P}_PORT_${s.name.toUpperCase()} && slot="${s.name}"`);
  }
  lines.push(`    echo ""`);
  lines.push('    echo -e "  ${_C_BGREEN}Dev server${_C_RESET} ${_C_DIM}·${_C_RESET} ${_C_WHITE}${slot}${_C_RESET} ${_C_DIM}·${_C_RESET} ${_C_CYAN}http://localhost:${port}${_C_RESET}"');
  lines.push('    echo -e "  ${_C_DIM}────────────────────────────────────────────${_C_RESET}"');
  lines.push(`    echo ""`);
  lines.push(`    PORT=$port npm run dev`);
  lines.push('}');
  lines.push('');

  // ================================================================
  // Daemon control functions (guardian-enabled projects only)
  // ================================================================
  if (config.guardian?.enabled) {
    lines.push('# =============================================================================');
    lines.push('# Daemon Control (Two-Process Architecture)');
    lines.push('# =============================================================================');
    lines.push('# Run each in its own terminal tab for independent restart/monitoring.');
    lines.push('# Exit code 75 = "code changed, pull + restart"');
    lines.push('# Exit code 0  = clean shutdown (Ctrl+C), stop');
    lines.push('# Any other    = crash, restart after 10s');
    lines.push('');

    // orchestrator()
    lines.push('orchestrator() {');
    lines.push(`    printf '\\e]0;Orchestrator\\a'`);
    lines.push(`    printf '\\e]1;Orchestrator\\a'`);
    lines.push('    echo ""');
    lines.push(`    echo -e "  \${_C_BCYAN}Orchestrator\${_C_RESET}"`);
    lines.push(`    echo -e "  \${_C_DIM}Task claiming · execution · Slack · plans\${_C_RESET}"`);
    lines.push('    echo -e "  ${_C_DIM}────────────────────────────────────────────${_C_RESET}"');
    lines.push('    echo ""');
    lines.push(`    cd "$${P}_MAIN"`);
    lines.push('    while true; do');
    lines.push('        npx tsx scripts/orchestrator.ts --watch');
    lines.push('        local exit_code=$?');
    lines.push('        if [ "$exit_code" -eq 75 ]; then');
    lines.push('            echo ""');
    lines.push('            echo -e "  ${_C_BYELLOW}Code updated → pulling + restarting...${_C_RESET}"');
    lines.push('            git pull --rebase origin main');
    lines.push('            sleep 2');
    lines.push('            echo -e "  ${_C_BCYAN}Restarting Orchestrator...${_C_RESET}"');
    lines.push('            echo ""');
    lines.push('        elif [ "$exit_code" -eq 0 ]; then');
    lines.push('            echo ""');
    lines.push('            echo -e "  ${_C_DIM}Orchestrator stopped cleanly.${_C_RESET}"');
    lines.push('            break');
    lines.push('        else');
    lines.push('            echo ""');
    lines.push('            echo -e "  ${_C_RED}Orchestrator crashed${_C_RESET} ${_C_DIM}(exit $exit_code)${_C_RESET} → restarting in 10s..."');
    lines.push('            sleep 10');
    lines.push('            echo -e "  ${_C_BCYAN}Restarting Orchestrator...${_C_RESET}"');
    lines.push('            echo ""');
    lines.push('        fi');
    lines.push('    done');
    lines.push(`    printf '\\e]0;Orchestrator - stopped\\a'`);
    lines.push(`    printf '\\e]1;Orchestrator - stopped\\a'`);
    lines.push('}');
    lines.push('');

    // guardian()
    lines.push('guardian() {');
    lines.push(`    printf '\\e]0;Guardian\\a'`);
    lines.push(`    printf '\\e]1;Guardian\\a'`);
    lines.push('    echo ""');
    lines.push(`    echo -e "  \${_C_BBLUE}Guardian\${_C_RESET}"`);
    lines.push(`    echo -e "  \${_C_DIM}PR merge · auto-rebase · conflict resolution · CI fix\${_C_RESET}"`);
    lines.push('    echo -e "  ${_C_DIM}────────────────────────────────────────────${_C_RESET}"');
    lines.push('    echo ""');
    lines.push(`    cd "$${P}_MAIN"`);
    lines.push('    while true; do');
    lines.push('        npx tsx scripts/guardian-v2.ts --watch');
    lines.push('        local exit_code=$?');
    lines.push('        if [ "$exit_code" -eq 75 ]; then');
    lines.push('            echo ""');
    lines.push('            echo -e "  ${_C_BYELLOW}Code updated → pulling + restarting...${_C_RESET}"');
    lines.push('            git pull --rebase origin main');
    lines.push('            sleep 2');
    lines.push('            echo -e "  ${_C_BBLUE}Restarting Guardian...${_C_RESET}"');
    lines.push('            echo ""');
    lines.push('        elif [ "$exit_code" -eq 0 ]; then');
    lines.push('            echo ""');
    lines.push('            echo -e "  ${_C_DIM}Guardian stopped cleanly.${_C_RESET}"');
    lines.push('            break');
    lines.push('        else');
    lines.push('            echo ""');
    lines.push('            echo -e "  ${_C_RED}Guardian crashed${_C_RESET} ${_C_DIM}(exit $exit_code)${_C_RESET} → restarting in 10s..."');
    lines.push('            sleep 10');
    lines.push('            echo -e "  ${_C_BBLUE}Restarting Guardian...${_C_RESET}"');
    lines.push('            echo ""');
    lines.push('        fi');
    lines.push('    done');
    lines.push(`    printf '\\e]0;Guardian - stopped\\a'`);
    lines.push(`    printf '\\e]1;Guardian - stopped\\a'`);
    lines.push('}');
    lines.push('');

    // daemon-status alias
    lines.push(`alias daemon-status='curl -s "\${TRAQR_API_BASE:-${apiBase}}/daemon/status" | jq .'`);
    lines.push('');
  }

  // ================================================================
  // Dashboard function (Raqr TUI — works from any directory)
  // ================================================================
  lines.push('# =============================================================================');
  lines.push('# Raqr TUI Dashboard (Rust binary)');
  lines.push('# =============================================================================');
  lines.push('');
  lines.push('dashboard() {');
  lines.push(`    printf '\\e]0;Raqr Dashboard\\a'`);
  lines.push(`    printf '\\e]1;Raqr Dashboard\\a'`);
  lines.push(`    local _raqr_url="\${TRAQR_API_BASE:-${apiBase}}"`)
  lines.push('    _raqr_url="${_raqr_url%/api}"');  // strip trailing /api if present
  lines.push('    RAQR_API_URL="$_raqr_url" ~/.traqr/bin/raqr "$@"');
  lines.push('    local slot=""');
  for (const s of slots) {
    lines.push(`    [[ "$(pwd)" == *"${s.name}"* ]] && slot="${s.name}"`);
  }
  lines.push(`    printf '\\e]0;%s\\a' "\${slot:-terminal}"`);
  lines.push(`    printf '\\e]1;%s\\a' "\${slot:-terminal}"`);
  lines.push('}');
  lines.push('');

  return lines.join('\n') + '\n';
}

/**
 * Write alias file to ~/.traqr/aliases/{slug}.sh.
 * Creates directories as needed.
 */
export function writeAliasFile(
  config: TraqrConfig,
  options: AliasGeneratorOptions,
): string {
  const outputDir = options.outputDir || path.join(process.env.HOME || '', '.traqr', 'aliases');
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const filePath = path.join(outputDir, `${config.project.name}.sh`);
  const content = generateAliasContent(config, options);
  fs.writeFileSync(filePath, content, 'utf-8');

  return filePath;
}
