/**
 * @traqr/core — Configuration Schema
 *
 * Types, defaults, and starter packs for the Traqr platform.
 * Stored at .traqr/config.json in each project.
 * Generated by /traqr-init, read by all commands.
 */

// ============================================================
// Daemon & Guardian Configuration
// ============================================================

/**
 * Daemon orchestration configuration.
 * Controls polling intervals, timeouts, concurrency, retry strategies,
 * and file paths for the daemon process.
 *
 * All timing values are in milliseconds.
 */
export interface DaemonConfig {
  /** API base URL for daemon coordination endpoints */
  apiBase: string;

  /** Temporary file paths used by daemon for state persistence */
  paths: {
    /** Processed Slack messages tracking */
    processed: string;
    /** Processed Linear issues tracking */
    processedIssues: string;
    /** Plan approval state */
    plans: string;
    /** Claude question queue */
    questionQueue: string;
    /** Answered questions log */
    answeredQuestions: string;
    /** Processed analytics events */
    processedAnalytics: string;
    /** Automation metrics */
    metrics: string;
    /** Guardian temporary working directory (relative to worktrees base) */
    guardianTemp: string;
  };

  /** Polling intervals (ms) */
  intervals: {
    /** Main loop poll interval (default: 10s) */
    poll: number;
    /** Supabase task queue poll interval (default: 30s) */
    taskPoll: number;
    /** Guardian merge loop interval (default: 30s) */
    guardian: number;
    /** Slack question check interval (default: 60s) */
    question: number;
    /** Analytics processing interval (default: 60s) */
    analytics: number;
    /** Plan approval check interval (default: 30s) */
    approvalCheck: number;
    /** Traffic monitoring interval (default: 15min) */
    trafficCheck: number;
    /** Health check interval when idle (default: 30min) */
    healthCheck: number;
    /** Slot sync check interval (default: 30s) */
    syncCheck: number;
    /** Agent heartbeat interval (default: 60s) */
    heartbeat: number;
  };

  /** Timeout values (ms) */
  timeouts: {
    /** Default fetch timeout (default: 30s) */
    defaultFetch: number;
    /** Quick fetch timeout for non-critical requests (default: 3s) */
    quickFetch: number;
    /** Git operation timeout (default: 30s) */
    git: number;
    /** Quick git operations like status/branch (default: 5s) */
    gitQuick: number;
    /** Git worktree removal timeout (default: 15s) */
    gitRemove: number;
    /** Plan approval wait timeout (default: 5min) */
    planApproval: number;
    /** Maximum implementation time (default: 30min) */
    implementation: number;
    /** Stall detection for tool calls (default: 5min) */
    toolCallStall: number;
    /** npm build timeout (default: 2min) */
    npmBuild: number;
    /** Plan approval TTL before auto-expiry (default: 24h) */
    planApprovalTTL: number;
    /** Pause/hold expiration time (default: 2h) */
    pauseExpiration: number;
    /** Window for detecting rework cycles (default: 30min) */
    reworkDetection: number;
    /** Adaptive timeout per changed file (default: 3min) */
    perFileAdaptive: number;
    /** Maximum adaptive timeout cap (default: 30min) */
    maxAdaptive: number;
    /** Divergence check cache TTL (default: 25s) */
    divergenceCache: number;
    /** Minimum wait before checking approval (default: 30s) */
    minApprovalWait: number;
  };

  /** Concurrency and failure limits */
  concurrency: {
    /** Maximum concurrent tasks (Walk=2, Run=all slots) */
    maxTasks: number;
    /** Max failures per ticket before giving up */
    maxTicketFailures: number;
    /** Max retries for in-function operations */
    maxRetries: number;
  };

  /** Per-reaction-type retry strategies for Guardian */
  retryStrategies: {
    ciFailed: { retries: number; escalateAfterMs: number };
    mergeConflicts: { retries: number; escalateAfterMs: number };
    stale: { retries: number; escalateAfterMs: number };
    feedbackPending: { retries: number; escalateAfterMs: number };
  };

  /** Query and result limits */
  queryLimits: {
    /** Max PRs to list from GitHub (default: 50) */
    prList: number;
    /** Max Slack channels to list (default: 200) */
    slackChannelList: number;
    /** Max Slack messages to fetch (default: 50) */
    slackFetchMessages: number;
    /** Memory search result limit (default: 10) */
    memorySearch: number;
    /** Gotcha search result limit (default: 5) */
    gotchaSearch: number;
    /** Max Slack thread scan iterations (default: 3) */
    maxThreadScans: number;
    /** Recent activity cap for metrics (default: 100) */
    recentActivityCap: number;
    /** Error message substring limit for logging (default: 200) */
    errorSubstringLimit: number;
  };
}

/**
 * Guardian merge lifecycle configuration (CLI-level).
 * Controls the automated PR merge pipeline behavior.
 * Stored in .traqr/config.json under the `guardian` key.
 */
export interface GuardianConfig {
  /** Whether Guardian is enabled (env: GUARDIAN_ENABLED) */
  enabled: boolean;

  /** Dry-run mode — actions logged but not executed (env: GUARDIAN_DRY_RUN) */
  dryRun: boolean;

  /** GitHub label that identifies PRs for Guardian to manage */
  prLabel: string;

  /** Phase timeout durations (ms) — auto-reset if stuck */
  phaseTimeouts: {
    /** Rebase phase timeout (default: 5min) */
    rebasing: number;
    /** Merge phase timeout (default: 30min) */
    merging: number;
    /** Conflict resolution phase timeout (default: 30min) */
    resolving: number;
  };

  /** Linear label configuration for ticket lifecycle */
  labels: {
    /** Label for tickets ready for agent pickup */
    agentReady: string;
    /** Label applied when agent claims a ticket */
    agentClaimed: { name: string; color: string };
    /** Label indicating ticket has an implementation plan */
    hasPlan: string;
  };
}

/**
 * Default daemon configuration.
 * All timing values tuned from production experience.
 */
export function getDefaultDaemonConfig(projectName: string): DaemonConfig {
  const prefix = projectName || 'traqr';
  return {
    apiBase: 'http://localhost:3000/api',
    paths: {
      processed: `/tmp/${prefix}-daemon-processed.json`,
      processedIssues: `/tmp/${prefix}-daemon-processed-issues.json`,
      plans: `/tmp/${prefix}-daemon-plans.json`,
      questionQueue: `/tmp/${prefix}-claude-tasks.json`,
      answeredQuestions: `/tmp/${prefix}-answered-questions.json`,
      processedAnalytics: `/tmp/${prefix}-daemon-analytics-processed.json`,
      metrics: `/tmp/${prefix}-automation-metrics.json`,
      guardianTemp: '.guardian-tmp',
    },
    intervals: {
      poll: 10_000,
      taskPoll: 30_000,
      guardian: 60_000,
      question: 60_000,
      analytics: 60_000,
      approvalCheck: 30_000,
      trafficCheck: 15 * 60_000,
      healthCheck: 30 * 60_000,
      syncCheck: 300_000,
      heartbeat: 60_000,
    },
    timeouts: {
      defaultFetch: 30_000,
      quickFetch: 3_000,
      git: 30_000,
      gitQuick: 5_000,
      gitRemove: 15_000,
      planApproval: 5 * 60_000,
      implementation: 30 * 60_000,
      toolCallStall: 5 * 60_000,
      npmBuild: 120_000,
      planApprovalTTL: 24 * 60 * 60_000,
      pauseExpiration: 2 * 60 * 60_000,
      reworkDetection: 30 * 60_000,
      perFileAdaptive: 3 * 60_000,
      maxAdaptive: 30 * 60_000,
      divergenceCache: 25_000,
      minApprovalWait: 30_000,
    },
    concurrency: {
      maxTasks: 2,
      maxTicketFailures: 3,
      maxRetries: 3,
    },
    retryStrategies: {
      ciFailed: { retries: 2, escalateAfterMs: 15 * 60_000 },
      mergeConflicts: { retries: 1, escalateAfterMs: 10 * 60_000 },
      stale: { retries: 2, escalateAfterMs: 10 * 60_000 },
      feedbackPending: { retries: 1, escalateAfterMs: 30 * 60_000 },
    },
    queryLimits: {
      prList: 50,
      slackChannelList: 200,
      slackFetchMessages: 50,
      memorySearch: 10,
      gotchaSearch: 5,
      maxThreadScans: 3,
      recentActivityCap: 100,
      errorSubstringLimit: 200,
    },
  };
}

/**
 * Default guardian configuration.
 * Safe defaults: disabled, dry-run on, conservative timeouts.
 */
export const DEFAULT_GUARDIAN_CONFIG: GuardianConfig = {
  enabled: false,
  dryRun: true,
  prLabel: 'daemon-pr',
  phaseTimeouts: {
    rebasing: 5 * 60_000,
    merging: 30 * 60_000,
    resolving: 30 * 60_000,
  },
  labels: {
    agentReady: 'agent-ready',
    agentClaimed: { name: 'agent-claimed', color: '#E67E22' },
    hasPlan: 'has-plan',
  },
};

// ============================================================
// Design DNA Configuration
// ============================================================

export interface DesignPalette {
  primary: string;
  secondary: string;
  accent: string;
  background: string;
  foreground: string;
  card: string;
  border: string;
  muted: string;
}

export interface DesignConfig {
  /** Design flavor preset */
  flavor: 'terminal' | 'playful' | 'minimal' | 'bold' | 'custom';
  /** Light mode color palette */
  palette: DesignPalette;
  /** Dark mode overrides (bg, fg, card, border, muted) */
  darkPalette?: {
    background: string;
    foreground: string;
    card: string;
    border: string;
    muted: string;
  };
  /** Font configuration */
  fonts: {
    sans: string;
    mono: string;
    /** Google Fonts import names, e.g. ['Inter', 'JetBrains_Mono'] */
    googleFonts: string[];
  };
  /** Border radius level */
  borderRadius: 'sharp' | 'medium' | 'rounded' | 'pill';
  /** Animation intensity */
  animations: 'none' | 'subtle' | 'smooth' | 'bouncy';
  /** Shadow intensity */
  shadows: 'none' | 'soft' | 'medium' | 'dramatic';
  /** Whether to include framer-motion dependency */
  useFramerMotion: boolean;
  /** Enable dark mode toggle support */
  darkMode: boolean;
  /** App display name shown in shell/sidebar */
  appDisplayName?: string;
}

/**
 * Border radius mapping per level.
 * Maps borderRadius setting to Tailwind classes at 4 sizes.
 */
export const BORDER_RADIUS_MAP: Record<
  DesignConfig['borderRadius'],
  { sm: string; md: string; lg: string; card: string }
> = {
  sharp:   { sm: 'rounded-none', md: 'rounded-sm',   lg: 'rounded-md',  card: 'rounded-lg'  },
  medium:  { sm: 'rounded-md',   md: 'rounded-lg',   lg: 'rounded-xl',  card: 'rounded-2xl' },
  rounded: { sm: 'rounded-xl',   md: 'rounded-2xl',  lg: 'rounded-3xl', card: 'rounded-3xl' },
  pill:    { sm: 'rounded-full', md: 'rounded-full',  lg: 'rounded-full', card: 'rounded-full' },
};

/**
 * Animation parameter mapping per intensity level.
 */
export const ANIMATION_PARAMS: Record<
  DesignConfig['animations'],
  {
    transitionDuration: string;
    entranceY: string;
    hoverLift: string;
    hoverScale: string;
    springStiffness: string;
    springDamping: string;
  }
> = {
  none:   { transitionDuration: '0ms',   entranceY: '0px',  hoverLift: '0px',  hoverScale: '1',     springStiffness: '0',   springDamping: '0'   },
  subtle: { transitionDuration: '150ms', entranceY: '4px',  hoverLift: '-1px', hoverScale: '1.01',  springStiffness: '300', springDamping: '30'  },
  smooth: { transitionDuration: '200ms', entranceY: '8px',  hoverLift: '-2px', hoverScale: '1.02',  springStiffness: '260', springDamping: '25'  },
  bouncy: { transitionDuration: '300ms', entranceY: '16px', hoverLift: '-4px', hoverScale: '1.05',  springStiffness: '200', springDamping: '15'  },
};

/**
 * Design flavor defaults — full presets for each visual style.
 */
export const DESIGN_FLAVOR_DEFAULTS: Record<
  'terminal' | 'playful' | 'minimal' | 'bold',
  DesignConfig
> = {
  terminal: {
    flavor: 'terminal',
    palette: {
      primary: '#00D4AA',
      secondary: '#6366F1',
      accent: '#F59E0B',
      background: '#0F172A',
      foreground: '#E2E8F0',
      card: '#1E293B',
      border: '#334155',
      muted: '#64748B',
    },
    fonts: { sans: 'Inter', mono: 'JetBrains Mono', googleFonts: ['Inter', 'JetBrains_Mono'] },
    borderRadius: 'sharp',
    animations: 'subtle',
    shadows: 'none',
    useFramerMotion: false,
    darkMode: false, // already dark by default
  },
  playful: {
    flavor: 'playful',
    palette: {
      primary: '#7FDBB6',
      secondary: '#A8D8EA',
      accent: '#FFB4A2',
      background: '#FEF9E7',
      foreground: '#2D3436',
      card: '#FFFFFF',
      border: '#E8E0D0',
      muted: '#9CA3AF',
    },
    darkPalette: {
      background: '#2A3D3D',
      foreground: '#E2E8F0',
      card: '#3D4F4A',
      border: '#4A5E56',
      muted: '#6B7B74',
    },
    fonts: { sans: 'Nunito', mono: 'Fira Code', googleFonts: ['Nunito', 'Fira_Code'] },
    borderRadius: 'rounded',
    animations: 'bouncy',
    shadows: 'medium',
    useFramerMotion: true,
    darkMode: true,
  },
  minimal: {
    flavor: 'minimal',
    palette: {
      primary: '#2563EB',
      secondary: '#6B7280',
      accent: '#059669',
      background: '#FFFFFF',
      foreground: '#111827',
      card: '#F9FAFB',
      border: '#E5E7EB',
      muted: '#9CA3AF',
    },
    darkPalette: {
      background: '#0A0A0A',
      foreground: '#FAFAFA',
      card: '#171717',
      border: '#262626',
      muted: '#737373',
    },
    fonts: { sans: 'Inter', mono: 'Geist Mono', googleFonts: ['Inter', 'Geist_Mono:ital,wght@0,100..900'] },
    borderRadius: 'medium',
    animations: 'subtle',
    shadows: 'soft',
    useFramerMotion: false,
    darkMode: true,
  },
  bold: {
    flavor: 'bold',
    palette: {
      primary: '#7C3AED',
      secondary: '#EC4899',
      accent: '#F59E0B',
      background: '#18181B',
      foreground: '#FAFAFA',
      card: '#27272A',
      border: '#3F3F46',
      muted: '#71717A',
    },
    fonts: { sans: 'Space Grotesk', mono: 'JetBrains Mono', googleFonts: ['Space_Grotesk', 'JetBrains_Mono'] },
    borderRadius: 'medium',
    animations: 'smooth',
    shadows: 'dramatic',
    useFramerMotion: true,
    darkMode: false, // already dark by default
  },
};

// ============================================================
// Required Services
// ============================================================

/**
 * Services that are always-on and non-skippable for Traqr projects.
 * During provisioning, these are processed in PASS 1.
 */
export const REQUIRED_SERVICES = ['github', 'supabase', 'posthog', 'vercel', 'slack'] as const;
export type RequiredService = (typeof REQUIRED_SERVICES)[number];

// ============================================================
// Main Configuration Interface
// ============================================================

export interface TraqrConfig {
  /** Schema version — '2.0.0' adds per-system tracking via `systems` map */
  version: '1.0.0' | '2.0.0';

  project: {
    /** Lowercase slug, e.g. "jiggycapital" */
    name: string;
    /** Display name, e.g. "Jiggy Capital" */
    displayName: string;
    /** Short description */
    description: string;
    /** Absolute path to main repo */
    repoPath: string;
    /** Absolute path to worktrees directory */
    worktreesPath: string;
    /** GitHub org/repo, e.g. "sean/jiggycapital" */
    ghOrgRepo: string;
    /** Framework detected (nextjs, node, python, rust, go, unknown) */
    framework?: string;
    /** Package manager (npm, yarn, pnpm, bun, pip, cargo) */
    packageManager?: string;
    /** Build command override */
    buildCommand?: string;
    /** Type-check command override */
    typecheckCommand?: string;
    /** Deployment platform (vercel, netlify, fly, railway, none) */
    deployPlatform?: string;
    /** Project type — determines which command steps apply (default: 'code') */
    type?: 'code' | 'life' | 'research';
  };

  /** Automation tier (0-4), derived from starterPack + customizations */
  tier: 0 | 1 | 2 | 3 | 4;

  /** Starter pack selection (entry point for wizard) */
  starterPack?: 'solo' | 'smart' | 'production' | 'full' | 'custom';

  /** Automation score (0-100), calculated from enabled features */
  automationScore?: number;

  /** Whether initialized in demo mode (no real API keys) */
  demo?: boolean;

  slots: {
    /** Number of marketing slots (default 1) */
    marketing?: number;
    /** Number of feature slots (default 5) */
    feature: number;
    /** Number of bugfix slots (default 5) */
    bugfix: number;
    /** Number of devops slots (default 5) */
    devops: number;
    /** Whether to include guardian/grunt slot (default true) */
    guardian?: boolean;
    /** Whether to include analysis slot (default false) */
    analysis: boolean;
  };

  ports: {
    /** Main repo port (default 3000) */
    main: number;
    /** First marketing port (default 3041) */
    marketingStart?: number;
    /** First feature port, increments by 1 (default 3001) */
    featureStart: number;
    /** First bugfix port, increments by 1 (default 3011) */
    bugfixStart: number;
    /** First devops port, increments by 1 (default 3021) */
    devopsStart: number;
    /** Guardian/grunt slot port (default 3031) */
    guardian?: number;
    /** Analysis slot port (default 3099) */
    analysis: number;
  };

  /** Short prefix for shell commands, e.g. "jiggy" -> jiggy-slots */
  prefix: string;

  /** 2-char alias prefix for multi-project shell aliases, e.g. "nk" -> nk1, nkc1 */
  aliasPrefix?: string;

  /** KV key namespace prefix for multi-project isolation, e.g. "nooktraqr" */
  kvPrefix?: string;

  /** Env var for authorized push, e.g. "JIGGYCAPITAL_SHIP_AUTHORIZED" */
  shipEnvVar: string;

  /** Session marker prefix, e.g. "jiggycapital" -> /tmp/jiggycapital-session-*.json */
  sessionPrefix: string;

  /** Co-author line for commits, e.g. "Claude Opus 4.6" */
  coAuthor: string;

  /** Memory configuration */
  memory?: {
    /** Memory provider: 'supabase' (full pgvector), 'local' (CLAUDE.md only), 'none' */
    provider: 'supabase' | 'local' | 'none';
    /** Memory API base URL, e.g. "https://nooktraqr.com/api" */
    apiBase?: string;
    /** Project slug in memory system */
    projectSlug?: string;
    /** Enable voice profile extraction */
    voiceProfiles?: boolean;
    /** Enable cross-project learning */
    crossProject?: boolean;
  };

  /** Obsidian vault configuration */
  vault?: {
    /** Absolute path to Obsidian vault root (e.g., '/Users/sean/Documents/Obsidian Vault') */
    path: string;
  };

  /** Issue tracking configuration */
  issues?: {
    /** Issue tracker provider */
    provider: 'linear' | 'github' | 'gitlab' | 'none';
    /** Linear team ID (required if provider is linear) */
    linearTeamId?: string;
    /** Linear workspace slug for URLs, e.g. "traqr-enterprises" → linear.app/traqr-enterprises/... */
    linearWorkspaceSlug?: string;
    /** Map of team key → team UUID for multi-team workspaces, e.g. { NTQ: "uuid1", TRQ: "uuid2" } */
    linearTeamMap?: Record<string, string>;
    /** Map of team key → Slack channel prefix, e.g. { NTQ: "nk", TRQ: "trq" } */
    channelPrefixMap?: Record<string, string>;
    /** Project ticket prefix for PR body parsing, e.g. "NTQ" for NookTraqr */
    ticketPrefix?: string;
    /** Enable plan-dispatch workflow */
    planDispatch?: boolean;
    /** Auto-create labels (agent-ready, has-plan, stale-*) */
    autoLabels?: boolean;
  };

  /** VCS (Version Control System) provider configuration */
  vcs?: {
    /** VCS provider: github or gitlab. Drives template conditionals and CLI tool selection. */
    provider: 'github' | 'gitlab';
    /** GitLab numeric project ID (required for GitLab API calls) */
    projectId?: string;
    /** Base URL for self-hosted instances (e.g., 'https://gitlab.aws.dev'). Defaults to github.com/gitlab.com */
    baseUrl?: string;
    /** Merge strategy: squash, fast-forward, or merge commit */
    mergeStrategy?: 'squash' | 'fast-forward' | 'merge';
    /** Enable auto-merge (GitHub: gh pr merge --auto, GitLab: merge_when_pipeline_succeeds) */
    autoMerge?: boolean;
    /** Enable primed-session pattern: GET before POST for corporate auth cookie establishment */
    primedSession?: boolean;
    /** Delete source branch after merge (GitLab setting) */
    removeSourceBranch?: boolean;
  };

  /** Notification configuration */
  notifications?: {
    /** Slack integration level */
    slackLevel: 'none' | 'basic' | 'standard' | 'full';
    /** Channel prefix for per-project channels (e.g., 'nk' for NookTraqr) */
    slackChannelPrefix?: string;
    /** Slack channel for PR notifications / merge buttons */
    slackDeployChannel?: string;
    /** Slack channel for triage/errors/Dev Inbox */
    slackTriageChannel?: string;
    /** Slack channel for analytics/signups */
    slackAnalyticsChannel?: string;
    /** Slack channel for user feedback log */
    slackFeedbackChannel?: string;
    /** Slack channel for marketing/newsletters */
    slackMarketingChannel?: string;
    /** Slack channel for archived threads */
    slackArchiveChannel?: string;
    /** Slack channel for ideas sounding board */
    slackIdeasChannel?: string;
    /** Slack channel for memory/learning notifications */
    slackMemoryChannel?: string;
    /** Slack channel for signup notifications */
    slackSignupsChannel?: string;
    /** Slack channel for control center status */
    slackControlCenterChannel?: string;
    /** Slack channel for cross-project dashboard aggregation */
    slackDashboardChannel?: string;
    /** Enable Dev Inbox (natural language ticket creation in Slack) */
    devInbox?: boolean;
    /** Enable Vibe Chat (brainstorming sessions in Slack threads) */
    vibeChat?: boolean;
  };

  /** Monitoring configuration */
  monitoring?: {
    /** Error tracking: sentry, axiom, or none */
    errorTracking: 'sentry' | 'axiom' | 'none';
    /** Analytics: posthog or none */
    analytics: 'posthog' | 'none';
    /** Uptime monitoring: checkly, betterstack, both, or none */
    uptime: 'checkly' | 'betterstack' | 'both' | 'none';
    /** Built-in user feedback widget */
    feedbackWidget: boolean;
    /** Observability: axiom or none */
    observability?: 'axiom' | 'none';
  };

  /** Auth provider configuration (per-project) */
  auth?: {
    /** Authentication provider */
    provider: 'firebase' | 'supabase' | 'clerk' | 'custom' | 'none';
  };

  /** Edge compute / KV configuration */
  edge?: {
    /** Edge provider */
    provider: 'cloudflare' | 'none';
    /** Cloudflare KV namespace ID (if provisioned) */
    kvNamespaceId?: string;
  };

  /** Email/marketing configuration */
  email?: {
    /** Email provider: resend or none */
    provider: 'resend' | 'none';
    /** Enabled email templates */
    templates: Array<
      'bug-fix' | 'feature-shipped' | 'welcome' | 'feedback-request' | 'weekly-recap' | 'marketing'
    >;
    /** Enable the full user feedback loop (bug -> fix -> email user) */
    feedbackLoop: boolean;
  };

  /** Cron job configuration — grouped by category */
  crons?: {
    /** Development health crons (slot status, stale branch cleanup, etc.) */
    devHealth: boolean;
    /** Analytics crons (engagement reports, traffic monitor, funnel analysis) */
    analytics: boolean;
    /** Issue tracking crons (ticket aging, backlog digest, SLA alerts) */
    issueTracking: boolean;
    /** Monitoring crons (proactive alerts, error digests) */
    monitoring: boolean;
    /** Memory system crons (learning synthesis, contradiction check) */
    memory: boolean;
    /** Marketing crons (newsletter schedule, unsubscribe cleanup) */
    marketing: boolean;
    /** Agent system crons (daemon health, session analysis) */
    agentSystem: boolean;
    /** Digest & report crons (daily/weekly summaries) */
    digests: boolean;
  };

  /** Daemon orchestration configuration (intervals, timeouts, concurrency) */
  daemon?: Partial<DaemonConfig>;

  /** Guardian merge lifecycle configuration */
  guardian?: Partial<GuardianConfig>;

  /** Design DNA configuration (visual flavor, palette, fonts, animations) */
  design?: DesignConfig;

  /** Monorepo sub-app configuration */
  monorepo?: {
    /** Whether this project is a monorepo with multiple apps */
    enabled: boolean;
    /** Directories containing apps (e.g. ['apps/nooktraqr', 'apps/platform']) */
    appDirs: string[];
    /** Per-app configuration overrides */
    apps: Record<string, {
      /** Human-readable app name */
      displayName: string;
      /** App directory relative to monorepo root (e.g. 'apps/pokotraqr') */
      appDir: string;
      /** Port offset for slot allocation (e.g. 0=3001, 1000=4001 for feature1) */
      portOffset: number;
      /** Auth provider override for this app */
      auth?: { provider: 'firebase' | 'supabase' | 'clerk' | 'custom' | 'none' };
      /** Framework override for this app */
      framework?: string;
      /** Workspace dependencies (e.g. ['@traqr/core', '@pokotraqr/data']) */
      workspaceDeps?: string[];
      /** Companion data package name (e.g. '@pokotraqr/data') */
      companionPackage?: string;
      /** Per-app Linear team ID (discovered or created during sub-app init) */
      linearTeamId?: string;
      /** Per-app ticket prefix for PR body parsing (e.g. "PKT") */
      ticketPrefix?: string;
      /** Per-app Slack channel prefix (e.g. "pk") */
      slackChannelPrefix?: string;
      /** Per-app Slack channels — maps purpose to channel name */
      slackChannels?: Record<string, string>;
    }>;
  };

  /** Template source configuration (for cross-project init) */
  templateSource?: {
    /** Where to load templates from */
    mode: 'local' | 'api';
    /** API URL for remote template loading (required if mode is 'api') */
    apiUrl?: string;
  };

  /** Service provisioning state — tracks how each service was set up */
  provisioning?: Record<string, {
    /** How the service was provisioned */
    method: 'mcp' | 'manual' | 'demo';
    /** ISO timestamp of provisioning */
    provisionedAt?: string;
    /** Env vars captured during provisioning */
    envVars?: string[];
  }>;

  /** Per-system skill tracking (v2) — records version, last applied, and audit state per sub-skill */
  systems?: Record<string, {
    /** Version of the sub-skill that last configured this system */
    skillVersion: string;
    /** ISO timestamp of when the sub-skill was last run in setup/upgrade mode */
    lastApplied: string;
    /** Last audit result, if audit has been run */
    lastAudit?: {
      timestamp: string;
      status: 'pass' | 'warn' | 'fail';
      gaps: number;
    };
  }>;
}

/**
 * Provisioning dependency tiers — services must be provisioned in this order.
 * Tier 1 services are provisioned first (others may depend on them).
 * All 11 services are represented across 4 tiers.
 */
export const PROVISIONING_TIERS: Array<{ tier: number; services: string[] }> = [
  { tier: 1, services: ['github', 'gitlab', 'supabase'] },
  { tier: 2, services: ['linear', 'slack', 'sentry'] },
  { tier: 3, services: ['posthog', 'resend', 'cloudflare', 'firebase', 'clerk'] },
  { tier: 4, services: ['vercel', 'axiom'] },
];

/**
 * Return services that need provisioning for a given config, in dependency order.
 * Returns two lists: required (always-on) and selected (user choices), both in tier order.
 */
export function getProvisioningOrder(config: TraqrConfig): string[] {
  const needed: string[] = [];
  for (const { services } of PROVISIONING_TIERS) {
    for (const svc of services) {
      switch (svc) {
        case 'github':
          // Required when VCS is GitHub (or no VCS specified — backward compat)
          if (!config.vcs?.provider || config.vcs.provider === 'github') needed.push(svc);
          break;
        case 'gitlab':
          // Required when VCS is GitLab
          if (config.vcs?.provider === 'gitlab') needed.push(svc);
          break;
        case 'supabase':
          // Required — database + memory foundation
          needed.push(svc);
          break;
        case 'posthog':
          // Required — analytics non-negotiable
          if (config.monitoring?.analytics !== 'none') needed.push(svc);
          break;
        case 'vercel':
          // Required — deployment platform
          if (config.project.deployPlatform === 'vercel' || config.project.deployPlatform === undefined) needed.push(svc);
          break;
        case 'slack':
          // Required — notification hub
          if (config.notifications?.slackLevel && config.notifications.slackLevel !== 'none') needed.push(svc);
          break;
        case 'linear':
          if (config.issues?.provider === 'linear') needed.push(svc);
          break;
        case 'sentry':
          if (config.monitoring?.errorTracking === 'sentry') needed.push(svc);
          break;
        case 'resend':
          if (config.email?.provider === 'resend') needed.push(svc);
          break;
        case 'cloudflare':
          if (config.edge?.provider === 'cloudflare' || config.daemon) needed.push(svc);
          break;
        case 'firebase':
          if (config.auth?.provider === 'firebase') needed.push(svc);
          break;
        case 'clerk':
          if (config.auth?.provider === 'clerk') needed.push(svc);
          break;
        case 'axiom':
          if (config.monitoring?.observability === 'axiom') needed.push(svc);
          break;
      }
    }
  }
  return needed;
}

/**
 * Split provisioning order into required (PASS 1) and selected (PASS 2) services.
 */
export function getProvisioningPasses(config: TraqrConfig): { pass1: string[]; pass2: string[] } {
  const all = getProvisioningOrder(config);
  const requiredSet = new Set<string>(REQUIRED_SERVICES);
  return {
    pass1: all.filter(s => requiredSet.has(s)),
    pass2: all.filter(s => !requiredSet.has(s)),
  };
}

/**
 * Mock environment variables for demo mode.
 * Used when `config.demo === true` to generate a working `.env.local`
 * without requiring real API keys.
 */
export const DEMO_ENV_VARS: Record<string, Record<string, string>> = {
  github: {
    // GitHub uses OAuth via MCP — no env vars needed, but track for completeness
    GITHUB_REPO: 'demo-org/demo-project',
  },
  supabase: {
    SUPABASE_URL: 'https://demo-project.supabase.co',
    SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.demo-anon-key-not-real',
    SUPABASE_SERVICE_ROLE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.demo-service-role-not-real',
  },
  linear: {
    LINEAR_API_KEY: 'lin_api_demo_key_not_real',
    LINEAR_TEAM_ID: 'demo-team-id-00000000',
  },
  slack: {
    SLACK_BOT_TOKEN: 'xoxb-demo-token-not-real',
    SLACK_SIGNING_SECRET: 'demo-signing-secret-not-real',
  },
  sentry: {
    SENTRY_DSN: 'https://demo@o0.ingest.sentry.io/0',
    SENTRY_ORG: 'demo-org',
    SENTRY_PROJECT: 'demo-project',
  },
  posthog: {
    NEXT_PUBLIC_POSTHOG_KEY: 'phc_demo_key_not_real',
    NEXT_PUBLIC_POSTHOG_HOST: 'https://us.i.posthog.com',
  },
  resend: {
    RESEND_API_KEY: 're_demo_key_not_real',
  },
  cloudflare: {
    CLOUDFLARE_ACCOUNT_ID: 'demo-cf-account-id',
    CLOUDFLARE_API_TOKEN: 'demo-cf-api-token-not-real',
  },
  firebase: {
    FIREBASE_API_KEY: 'demo-firebase-api-key',
    FIREBASE_AUTH_DOMAIN: 'demo-project.firebaseapp.com',
    FIREBASE_PROJECT_ID: 'demo-project',
  },
  clerk: {
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: 'pk_test_demo-clerk-key-not-real',
    CLERK_SECRET_KEY: 'sk_test_demo-clerk-secret-not-real',
  },
  vercel: {
    VERCEL_TOKEN: 'demo-vercel-token-not-real',
  },
  axiom: {
    AXIOM_TOKEN: 'xaat-demo-axiom-token-not-real',
    AXIOM_DATASET: 'demo-logs',
  },
};

/**
 * Build provisioning state for demo mode.
 * All selected services get `method: 'demo'` with mock env vars.
 */
export function getDemoProvisioningState(
  config: TraqrConfig
): Record<string, { method: 'demo'; provisionedAt: string; envVars: string[] }> {
  const services = getProvisioningOrder(config);
  const now = new Date().toISOString();
  const state: Record<string, { method: 'demo'; provisionedAt: string; envVars: string[] }> = {};

  for (const svc of services) {
    const vars = DEMO_ENV_VARS[svc];
    if (vars) {
      state[svc] = {
        method: 'demo',
        provisionedAt: now,
        envVars: Object.keys(vars),
      };
    }
  }

  return state;
}

/**
 * Starter pack defaults — used by the wizard to pre-fill selections.
 */
export const STARTER_PACK_DEFAULTS: Record<
  'solo' | 'smart' | 'production' | 'full',
  Partial<TraqrConfig>
> = {
  solo: {
    tier: 0,
    starterPack: 'solo',
    slots: { feature: 3, bugfix: 1, devops: 0, analysis: false },
    memory: undefined,
    issues: undefined,
    notifications: undefined,
    monitoring: undefined,
    email: undefined,
    crons: undefined,
  },
  smart: {
    tier: 2,
    starterPack: 'smart',
    slots: { feature: 3, bugfix: 2, devops: 1, analysis: false },
    memory: { provider: 'supabase' },
    issues: { provider: 'github', planDispatch: true, autoLabels: true },
    notifications: undefined,
    monitoring: undefined,
    email: undefined,
    crons: { devHealth: true, analytics: false, issueTracking: true, monitoring: false, memory: true, marketing: false, agentSystem: false, digests: false },
  },
  production: {
    tier: 3,
    starterPack: 'production',
    slots: { feature: 3, bugfix: 2, devops: 3, analysis: true },
    memory: { provider: 'supabase', crossProject: true },
    issues: { provider: 'linear', ticketPrefix: undefined, planDispatch: true, autoLabels: true },
    notifications: { slackLevel: 'standard', slackAnalyticsChannel: 'analytics' },
    monitoring: { errorTracking: 'sentry', analytics: 'posthog', uptime: 'none', feedbackWidget: true },
    email: undefined,
    crons: { devHealth: true, analytics: true, issueTracking: true, monitoring: true, memory: true, marketing: false, agentSystem: false, digests: true },
    daemon: { concurrency: { maxTasks: 1, maxTicketFailures: 3, maxRetries: 3 } },
    guardian: { enabled: false, dryRun: true },
  },
  full: {
    tier: 4,
    starterPack: 'full',
    slots: { feature: 3, bugfix: 2, devops: 3, analysis: true },
    memory: { provider: 'supabase', crossProject: true, voiceProfiles: true },
    issues: { provider: 'linear', ticketPrefix: undefined, planDispatch: true, autoLabels: true },
    notifications: { slackLevel: 'full', slackAnalyticsChannel: 'analytics', slackFeedbackChannel: 'dev-triage', slackMarketingChannel: 'marketing', slackArchiveChannel: 'dev-archive', slackIdeasChannel: 'dev-ideas', slackMemoryChannel: 'memory', slackSignupsChannel: 'analytics', slackControlCenterChannel: 'control-center', slackDashboardChannel: 'analytics', devInbox: true, vibeChat: true },
    monitoring: { errorTracking: 'sentry', analytics: 'posthog', uptime: 'both', feedbackWidget: true },
    email: { provider: 'resend', templates: ['bug-fix', 'feature-shipped', 'welcome', 'feedback-request', 'weekly-recap', 'marketing'], feedbackLoop: true },
    crons: { devHealth: true, analytics: true, issueTracking: true, monitoring: true, memory: true, marketing: true, agentSystem: true, digests: true },
    daemon: { concurrency: { maxTasks: 2, maxTicketFailures: 3, maxRetries: 3 } },
    guardian: { enabled: true, dryRun: true },
  },
};

/**
 * Golden Path presets — opinionated VCS + issues + notifications bundles.
 * Each path extends a starter pack with VCS-specific defaults.
 * Used by `traqr init` to suggest the right config based on environment detection.
 */
export const GOLDEN_PATH_DEFAULTS: Record<
  'github-pro' | 'gitlab-team' | 'gitlab-minimal',
  { starterPack: 'solo' | 'smart' | 'production' | 'full'; vcsOverrides: Partial<TraqrConfig> }
> = {
  'github-pro': {
    starterPack: 'production',
    vcsOverrides: {
      vcs: { provider: 'github' },
      issues: { provider: 'linear', planDispatch: true, autoLabels: true },
      notifications: { slackLevel: 'standard' },
    },
  },
  'gitlab-team': {
    starterPack: 'smart',
    vcsOverrides: {
      vcs: { provider: 'gitlab', autoMerge: true, primedSession: true, removeSourceBranch: true },
      issues: { provider: 'gitlab', planDispatch: true, autoLabels: true },
      notifications: { slackLevel: 'none' as const },
    },
  },
  'gitlab-minimal': {
    starterPack: 'solo',
    vcsOverrides: {
      vcs: { provider: 'gitlab' },
      issues: { provider: 'none' },
    },
  },
};

/**
 * Calculate automation score (0-100) from config.
 */
export function calculateAutomationScore(config: TraqrConfig): number {
  let score = 0;

  // Slots: up to 15 points
  const totalSlots = (config.slots.marketing || 0) + config.slots.feature + config.slots.bugfix + config.slots.devops + (config.slots.guardian ? 1 : 0) + (config.slots.analysis ? 1 : 0);
  score += Math.min(15, totalSlots * 2);

  // Memory: up to 20 points
  if (config.memory?.provider === 'supabase') {
    score += 15;
    if (config.memory.crossProject) score += 3;
    if (config.memory.voiceProfiles) score += 2;
  } else if (config.memory?.provider === 'local') {
    score += 10;
  }

  // Issues: up to 15 points
  if (config.issues?.provider === 'linear') {
    score += 10;
    if (config.issues.planDispatch) score += 3;
    if (config.issues.autoLabels) score += 2;
  } else if (config.issues?.provider === 'github') {
    score += 7;
    if (config.issues.planDispatch) score += 3;
  } else if (config.issues?.provider === 'gitlab') {
    score += 7;
    if (config.issues.planDispatch) score += 3;
  }

  // Slack: up to 15 points
  if (config.notifications?.slackLevel === 'full') {
    score += 15;
  } else if (config.notifications?.slackLevel === 'standard') {
    score += 10;
  } else if (config.notifications?.slackLevel === 'basic') {
    score += 5;
  }

  // Monitoring: up to 15 points
  if (config.monitoring) {
    if (config.monitoring.errorTracking !== 'none') score += 4;
    if (config.monitoring.analytics !== 'none') score += 4;
    if (config.monitoring.uptime === 'both') score += 4;
    else if (config.monitoring.uptime !== 'none') score += 3;
    if (config.monitoring.feedbackWidget) score += 3;
    // Observability: +2 bonus
    if (config.monitoring.observability === 'axiom') score += 2;
  }

  // Auth: up to 3 points
  if (config.auth?.provider && config.auth.provider !== 'none') {
    score += 3;
  }

  // Edge: up to 3 points
  if (config.edge?.provider === 'cloudflare') {
    score += 3;
  }

  // Email: up to 10 points
  if (config.email) {
    if (config.email.provider !== 'none') score += 3;
    score += Math.min(5, config.email.templates.length);
    if (config.email.feedbackLoop) score += 2;
  }

  // Crons: up to 10 points
  if (config.crons) {
    const enabledCrons = Object.values(config.crons).filter(Boolean).length;
    score += Math.min(10, enabledCrons * 1.25);
  }

  return Math.min(100, Math.round(score));
}

// ============================================================
// Config v2 Migration
// ============================================================

/**
 * Migrate a v1 config to v2 by adding the `systems` tracking map.
 * Idempotent — returns the config unchanged if already v2.
 * Preserves all existing fields.
 */
export function migrateConfigV1ToV2(config: TraqrConfig): TraqrConfig {
  if (config.version === '2.0.0') return config;
  return {
    ...config,
    version: '2.0.0' as const,
    systems: {},
  };
}

/**
 * Type guard: returns true if the config has been migrated to v2
 * (has version 2.0.0 and a systems map).
 */
export function isConfigV2(config: TraqrConfig): boolean {
  return config.version === '2.0.0' && config.systems !== undefined;
}
