/**
 * @traqr/core — MOTD Generator
 *
 * Generates ~/.traqr/motd.sh — a shell script that displays a
 * project-aware welcome screen when the terminal opens.
 *
 * Reads from the org config (~/.traqr/config.json) and each
 * registered project's .traqr/config.json to build a bash function
 * with dynamic time/date and ANSI gradient colors.
 */

import * as fs from 'fs';
import * as path from 'path';
import { loadOrgConfig } from './config-resolver.js';
import { loadProjectConfig } from './config-resolver.js';

// ============================================================
// Helpers
// ============================================================

/** Wrap text in shell color var references for echo -e output */
function sh(varName: string, text: string): string {
  return '${' + varName + '}' + text + '${_R}';
}

// ============================================================
// Generator
// ============================================================

/**
 * Generate the MOTD shell script content.
 * Returns the full shell script as a string.
 */
export function generateMotdContent(): string {
  const { config: orgConfig } = loadOrgConfig();
  const projects = orgConfig?.projects || {};
  const primarySlug = orgConfig?.primaryProject;
  const slugs = Object.keys(projects);

  const lines: string[] = [];
  lines.push('#!/bin/bash');
  lines.push('# Generated by Traqr. Regenerate with: traqr init (or traqr setup)');
  lines.push('');
  lines.push('_traqr_motd() {');

  // ANSI color variables (computed once inside the function)
  lines.push("  local _R=$'\\033[0m'");
  lines.push("  local _B=$'\\033[1m'");
  lines.push("  local _D=$'\\033[2m'");
  lines.push("  local _W=$'\\033[1;37m'");
  lines.push("  local _G1=$'\\033[38;5;44m'");
  lines.push("  local _G2=$'\\033[38;5;45m'");
  lines.push("  local _G3=$'\\033[38;5;75m'");
  lines.push("  local _G4=$'\\033[38;5;111m'");
  lines.push("  local _G5=$'\\033[38;5;147m'");
  lines.push("  local _BC=$'\\033[1;36m'");
  lines.push("  local _BB=$'\\033[1;34m'");
  lines.push("  local _BP=$'\\033[1;35m'");
  lines.push('');

  // Dynamic time computation at shell runtime
  lines.push('  local hour=$(date +%H)');
  lines.push('  local greeting');
  lines.push('  if   [ "$hour" -lt 6  ]; then greeting="Late night mode"');
  lines.push('  elif [ "$hour" -lt 12 ]; then greeting="Good morning"');
  lines.push('  elif [ "$hour" -lt 17 ]; then greeting="Good afternoon"');
  lines.push('  elif [ "$hour" -lt 21 ]; then greeting="Good evening"');
  lines.push('  else                          greeting="Night owl hours"');
  lines.push('  fi');
  lines.push('  local date_str=$(date "+%a %b %-d, %-I:%M %p")');
  lines.push('');

  // Gradient horizontal rule
  lines.push('  local gline="${_G1}────────────${_G2}────────────${_G3}────────────${_G4}────────────${_G5}────────────${_R}"');

  // Load monorepo app data from primary project config
  let monorepoApps: Record<string, any> = {};
  let primaryKey = '';
  let primary: any = null;
  let primarySlots: { feature: number; bugfix: number; devops: number; marketing?: number; guardian?: boolean; analysis: boolean } | null = null;
  let prefixName = '';

  if (slugs.length > 0) {
    primaryKey = primarySlug && projects[primarySlug] ? primarySlug : slugs[0];
    primary = projects[primaryKey];
    try {
      const { config: projConfig } = loadProjectConfig(primary.repoPath);
      if (projConfig?.monorepo?.enabled && projConfig.monorepo.apps) {
        monorepoApps = projConfig.monorepo.apps;
      }
      if (projConfig) {
        primarySlots = projConfig.slots;
        prefixName = projConfig.prefix || primary.aliasPrefix;
      }
    } catch {
      prefixName = primary?.aliasPrefix || '';
    }
  }

  // Subtitle: monorepo-aware
  const appCount = Object.keys(monorepoApps).length;
  const subtitle = appCount > 0
    ? `Traqr Monorepo · ${appCount} apps`
    : 'Traqr Monorepo';

  // Brand text with gradient
  lines.push('');
  lines.push('  echo ""');
  lines.push('  echo -e "   ${gline}"');
  lines.push('  echo -e "       ${_B}/\\\\___/\\\\${_R}            ${_G1}${_B}T  ${_G2}R  ${_G3}A  ${_G4}Q  ${_G5}R${_R}"');
  lines.push('  echo -e "      ${_B}(${_R} ${_G3}●${_R}   ${_G3}●${_R} ${_B})${_R}           ${_W}${greeting}${_R} ${_D}· ${date_str}${_R}"');
  lines.push('  echo -e "      ${_B}(  =^=  )${_R}           ' + sh('_D', subtitle) + '"');
  lines.push('  echo -e "       ${_B}(______)${_R}"');
  lines.push('  echo -e "   ${gline}"');

  if (slugs.length === 0) {
    // No projects registered
    lines.push('  echo ""');
    lines.push('  echo -e "     ${_D}No projects set up yet.${_R}"');
    lines.push('  echo ""');
    lines.push('  echo -e "     ${_W}Get started:${_R}"');
    lines.push('  echo -e "       ${_W}traqr init${_R}       ${_D}Set up Traqr in any project${_R}"');
  } else {
    lines.push('  echo ""');

    // ---- Build Apps column (left side) ----
    const appLines: string[] = [];
    appLines.push('     ' + sh('_G2', 'Apps'));

    if (appCount > 0) {
      for (const [key, app] of Object.entries(monorepoApps)) {
        const prefix = app.ticketPrefix || '';
        const name = app.displayName || key;
        if (prefix) {
          appLines.push('     ' + sh('_W', prefix) + '  ' + sh('_D', name));
        } else {
          appLines.push('          ' + sh('_D', name));
        }
      }
    }

    // ---- Build Workspaces column (right side, top) ----
    const wsLines: string[] = [];
    wsLines.push(sh('_G3', 'Workspaces'));

    if (primarySlots) {
      const s = primarySlots;
      if (s.marketing && s.marketing > 0) {
        const range = s.marketing === 1
          ? sh('_W', 'ck1')
          : sh('_W', 'ck1') + sh('_D', '-') + sh('_W', 'ck' + s.marketing);
        wsLines.push('marketing ' + range);
      }
      if (s.feature > 0) {
        const range = s.feature === 1
          ? sh('_W', 'c1')
          : sh('_W', 'c1') + sh('_D', '-') + sh('_W', 'c' + s.feature);
        wsLines.push('feature   ' + range);
      }
      if (s.bugfix > 0) {
        const range = s.bugfix === 1
          ? sh('_W', 'cb1')
          : sh('_W', 'cb1') + sh('_D', '-') + sh('_W', 'cb' + s.bugfix);
        wsLines.push('bugfix    ' + range);
      }
      if (s.devops > 0) {
        const range = s.devops === 1
          ? sh('_W', 'cd1')
          : sh('_W', 'cd1') + sh('_D', '-') + sh('_W', 'cd' + s.devops);
        wsLines.push('devops    ' + range);
      }
      if (s.guardian) {
        wsLines.push('guardian  ' + sh('_W', 'grunt'));
      }
      if (s.analysis) {
        wsLines.push(sh('_D', 'analysis') + '  ' + sh('_W', 'ca'));
      }
    }

    // ---- Agents sub-section (right side, below workspaces) ----
    const agentLines: string[] = [];
    agentLines.push('');
    agentLines.push(sh('_G4', 'Agents'));
    agentLines.push(sh('_BP', 'traqr') + ' ' + sh('_D', '[topic]'));
    agentLines.push(sh('_BB', 'guardian'));
    agentLines.push(sh('_G1', 'raqr') + '  ' + sh('_D', 'dashboard'));

    // Combine right column: workspaces + agents
    const rightLines = [...wsLines, ...agentLines];

    // Print side by side: Apps (left) | Workspaces + Agents (right)
    const colWidth = 38;
    const maxRows = Math.max(appLines.length, rightLines.length);
    for (let i = 0; i < maxRows; i++) {
      const left = appLines[i] || '';
      const right = rightLines[i] || '';
      if (right) {
        const visLeft = left.replace(/\$\{[^}]+\}/g, '');
        const visLen = visLeft.length;
        const pad = Math.max(1, colWidth - visLen);
        lines.push('  echo -e "' + left + ' '.repeat(pad) + right + '"');
      } else {
        lines.push('  echo -e "' + left + '"');
      }
    }

    // Secondary projects (non-primary, non-monorepo projects)
    const secondaries = slugs.filter(s => s !== primaryKey);
    if (secondaries.length > 0) {
      lines.push('  echo ""');
      for (const slug of secondaries) {
        const proj = projects[slug];
        const px = proj.aliasPrefix;
        const cmds = px + '1 ' + px + 'c1 ' + px + 'b1 ' + px + 'cb1';
        lines.push('  echo -e "     ' + sh('_W', proj.displayName) + '  ' + sh('_D', cmds + '    ' + px + '-slots · ' + px + '-sync') + '"');
      }
    }
  }

  // Footer
  lines.push('  echo ""');
  lines.push('  echo -e "   ${gline}"');

  // Build footer commands — modernized
  if (slugs.length > 0) {
    lines.push('  echo -e "     ' + sh('_D', prefixName + '-slots · ' + prefixName + '-sync · ' + prefixName + '-dev · ' + prefixName + '-prs · raqr') + '"');
    lines.push('  echo -e "     ' + sh('_D', 'traqr [topic] · traqr projects · traqr init') + '"');
  } else {
    lines.push('  echo -e "     ' + sh('_D', 'traqr init') + '"');
  }
  lines.push('  echo ""');

  lines.push('}');
  lines.push('');

  // Override legacy single-project MOTDs
  lines.push('# Override legacy single-project MOTDs');
  lines.push('_nook_motd() { :; }');
  lines.push('');

  // Auto-invoke
  lines.push('_traqr_motd');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate and write the MOTD to ~/.traqr/motd.sh.
 * Returns the file path written.
 */
export function generateMotd(): string {
  const motdDir = path.join(process.env.HOME || '', '.traqr');
  const motdPath = path.join(motdDir, 'motd.sh');

  if (!fs.existsSync(motdDir)) {
    fs.mkdirSync(motdDir, { recursive: true });
  }

  const content = generateMotdContent();
  fs.writeFileSync(motdPath, content, 'utf-8');

  return motdPath;
}
