/**
 * @traqr/core — Shell Init Generator
 *
 * Generates ~/.traqr/shell-init.sh — the single entry point that
 * replaces both worktree-aliases.sh and manual source lines.
 *
 * Structure:
 *   1. ANSI color variables (shared)
 *   2. CLI binary on PATH (per project)
 *   3. Smart traqr dispatcher
 *   4. Source per-project alias files
 *   5. MOTD
 */

import * as fs from 'fs';
import * as path from 'path';
import { loadOrgConfig } from './config-resolver.js';

// ============================================================
// Generator
// ============================================================

/**
 * Generate the shell-init.sh content.
 * Reads the org config to find registered projects and the primary project.
 */
export function generateShellInitContent(): string {
  const { config } = loadOrgConfig();
  const projects = config?.projects || {};
  const primaryProject = config?.primaryProject;

  // Find primary project's repo path for dispatcher
  let primaryRepoPath = '';
  if (primaryProject && projects[primaryProject]) {
    primaryRepoPath = projects[primaryProject].repoPath;
  } else {
    // Fall back to first registered project
    const firstKey = Object.keys(projects)[0];
    if (firstKey) {
      primaryRepoPath = projects[firstKey].repoPath;
    }
  }

  // Traqr platform repo path (for CLI binary)
  const traqrRepoPath = config?.traqrRepoPath || '';

  const lines: string[] = [];

  lines.push('#!/bin/bash');
  lines.push('# =============================================================================');
  lines.push('# Traqr Shell Init — Single entry point for all Traqr projects');
  lines.push('# Generated by Traqr. Regenerate with: traqr render');
  lines.push('# =============================================================================');
  lines.push('');

  // ANSI color variables (shared across all projects)
  lines.push('# ANSI color variables (shared)');
  lines.push("_C_RESET=$'\\033[0m'");
  lines.push("_C_BOLD=$'\\033[1m'");
  lines.push("_C_DIM=$'\\033[2m'");
  lines.push("_C_CYAN=$'\\033[0;36m'");
  lines.push("_C_GREEN=$'\\033[0;32m'");
  lines.push("_C_YELLOW=$'\\033[0;33m'");
  lines.push("_C_BLUE=$'\\033[0;34m'");
  lines.push("_C_PURPLE=$'\\033[0;35m'");
  lines.push("_C_RED=$'\\033[0;31m'");
  lines.push("_C_WHITE=$'\\033[1;37m'");
  lines.push("_C_BCYAN=$'\\033[1;36m'");
  lines.push("_C_BGREEN=$'\\033[1;32m'");
  lines.push("_C_BYELLOW=$'\\033[1;33m'");
  lines.push("_C_BBLUE=$'\\033[1;34m'");
  lines.push("_C_BPURPLE=$'\\033[1;35m'");
  lines.push('');

  // CLI binary on PATH — prefer traqr repo, fall back to primary project
  const cliPath = traqrRepoPath
    ? `${traqrRepoPath}/node_modules/.bin`
    : primaryRepoPath
      ? `${primaryRepoPath}/node_modules/.bin`
      : '';
  if (cliPath) {
    lines.push('# CLI binary on PATH');
    lines.push(`export PATH="${cliPath}:$PATH"`);
    lines.push('');
  }

  // Smart traqr dispatcher
  if (primaryRepoPath) {
    lines.push('# Smart traqr dispatcher');
    lines.push('traqr() {');
    lines.push('    case "$1" in');
    lines.push('        init|new|setup|projects|status|render|upgrade|--help|-h|--version|-v)');
    lines.push('            command traqr "$@" ;;');
    lines.push('        *)');
    lines.push(`            cd "${primaryRepoPath}"`);
    lines.push('            local topic="${1:-}"');
    lines.push("            printf '\\e]0;Traqr\\a'");
    lines.push("            printf '\\e]1;Traqr\\a'");
    lines.push('            if [ -n "$topic" ]; then');
    lines.push('                CLAUDE_CODE_DISABLE_TERMINAL_TITLE=1 claude "/advisor $topic"');
    lines.push('            else');
    lines.push('                CLAUDE_CODE_DISABLE_TERMINAL_TITLE=1 claude "/advisor"');
    lines.push('            fi');
    lines.push("            printf '\\e]0;Traqr - done\\a'");
    lines.push("            printf '\\e]1;Traqr - done\\a'");
    lines.push('            ;;');
    lines.push('    esac');
    lines.push('}');
    lines.push('');
  }

  // Source per-project alias files
  lines.push('# Source per-project alias files');
  lines.push('for f in ~/.traqr/aliases/*.sh; do [ -f "$f" ] && source "$f"; done');
  lines.push('');

  // MOTD
  lines.push('# MOTD');
  lines.push('[ -f ~/.traqr/motd.sh ] && source ~/.traqr/motd.sh');
  lines.push('');

  return lines.join('\n');
}

/**
 * Write shell-init.sh to ~/.traqr/shell-init.sh.
 * Creates directories as needed.
 * Returns the absolute path of the written file.
 */
export function writeShellInit(): string {
  const home = process.env.HOME || '';
  const dir = path.join(home, '.traqr');
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const filePath = path.join(dir, 'shell-init.sh');
  const content = generateShellInitContent();
  fs.writeFileSync(filePath, content, 'utf-8');

  return filePath;
}
